### ISSUE TITLE
Add python swift client

### ISSUE THREAD

**Issue by claresloggett** [gvlproject/gvl_commandline_utilities#9]
Temporary measure until it can get into the image build.

Requires:
sudo pip install python-lxml
sudo pip install python-keystoneclient
sudo pip install python-swiftclient

**Comment by madisonkeene** [comment]
Given this is from 2 years ago - can I assume this is no longer valid? @nuwang @claresloggett

**Comment by nuwang** [comment]
The python-swift-client is installed as a part of the python-genomespace-client now, so I think we can close this.
